suppressPackageStartupMessages(library("argparse"))

# create parser object
parser <- ArgumentParser()

# specify our desired options 
# by default ArgumentParser will add an help option 

parser$add_argument("-j", "--json", default=NULL,help="nf schema JSON generated by nf-core python library",required=TRUE)
parser$add_argument("-o","--output-xml","--output_xml",action="append", default=NULL, help = "output file name for parameters XML file")
parser$add_argument("-i","--include_hidden_parameters",action="store_true", default=FALSE, help = "include all parameters in XML")
parser$add_argument("-s","--sections_override", default=c("reference_genome_options"),action="append",help="section in schema JSON file to ensure it's presence in the output XML file")
# get command line options, if help option encountered print help and exit,
# otherwise if options not found on command line then set defaults, 
args <- parser$parse_args()

print(args)